#include "stdafx.h"
#include "LevelManager.h"
#include <fstream>


LevelManager::LevelManager() {
	multiplayerLevel = {
		PLAYER, FLOOR, BRICK, BRICK, BRICK, BRICK, BRICK, FLOOR, BRICK, BRICK, BRICK, FLOOR, BRICK, FLOOR, BRICK, BRICK, BRICK, FLOOR, FLOOR,
		FLOOR, WALL, FLOOR, WALL, BRICK, WALL, FLOOR, WALL, FLOOR, WALL, FLOOR, WALL, FLOOR, WALL, BRICK, WALL, FLOOR, WALL, FLOOR, WALL,
		BRICK, FLOOR, BRICK, FLOOR, BRICK, BRICK, BRICK, FLOOR, BRICK, FLOOR, BRICK, BRICK, BRICK, FLOOR, BRICK, FLOOR, BRICK, FLOOR, FLOOR,
		FLOOR, WALL, BRICK, WALL, BRICK, WALL, FLOOR, WALL, FLOOR, WALL, BRICK, WALL, BRICK, WALL, FLOOR, WALL, FLOOR, WALL, BRICK,
		BRICK, BRICK, FLOOR, BRICK, BRICK, FLOOR, BRICK, BRICK, BRICK, FLOOR, BRICK, FLOOR, BRICK, BRICK, BRICK, FLOOR, BRICK, FLOOR, FLOOR,
		BRICK, WALL, FLOOR, WALL, FLOOR, WALL, BRICK, WALL, FLOOR, WALL, FLOOR, WALL, FLOOR, WALL, FLOOR, WALL, BRICK, WALL, FLOOR,
		BRICK, FLOOR, BRICK, FLOOR, BRICK, FLOOR, BRICK, FLOOR, BRICK, FLOOR, BRICK, FLOOR, BRICK, FLOOR, BRICK, FLOOR, FLOOR, FLOOR, BRICK,
		FLOOR, WALL, BRICK, WALL, BRICK, WALL, BRICK, WALL, BRICK, WALL, BRICK, WALL, FLOOR, WALL, FLOOR, WALL, FLOOR, WALL, FLOOR,
		BRICK, FLOOR, BRICK, FLOOR, BRICK, FLOOR, BRICK, FLOOR, BRICK, FLOOR, BRICK, FLOOR, BRICK, FLOOR, PLAYER, FLOOR, WALL, FLOOR, WALL
	};	
	level1 = {
		PLAYER, FLOOR, BRICK, FLOOR, FLOOR, BRICK, BRICK, FLOOR, FLOOR, FLOOR, FLOOR, BRICK, BRICK, FLOOR, FLOOR, BRICK, FLOOR, BRICK, FLOOR,
		FLOOR, WALL, FLOOR, WALL, FLOOR, WALL, FLOOR, WALL, FLOOR, WALL, FLOOR, WALL, BRICK, WALL, BRICK, WALL, FLOOR, WALL, FLOOR,
		BRICK, BRICK, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, BRICK, BRICK, FLOOR, FLOOR, BRICK, BRICK, FLOOR, BRICK, FLOOR, FLOOR,
		FLOOR, WALL, FLOOR, WALL, FLOOR, WALL, FLOOR, WALL, FLOOR, WALL, FLOOR, WALL, ENEMY2, WALL, BRICK, WALL, BRICK, WALL, BRICK,
		FLOOR, FLOOR, BRICK, FLOOR, FLOOR, BRICK, FLOOR, FLOOR, FLOOR, BRICK, FLOOR, FLOOR, FLOOR, BRICK, FLOOR, BRICK, BRICK, FLOOR, FLOOR,
		FLOOR, WALL, BRICK, WALL, FLOOR, WALL, BRICK, WALL, FLOOR, WALL, BRICK, WALL, BRICK, WALL, BRICK, WALL, FLOOR, WALL, BRICK,
		FLOOR, BRICK, FLOOR, BRICK, ENEMY1, FLOOR, BRICK, FLOOR, BRICK, BRICK, FLOOR, BRICK, BRICK, FLOOR, BRICK, FLOOR, FLOOR, ENEMY3, FLOOR,
		BRICK, WALL, FLOOR, WALL, FLOOR, WALL, FLOOR, WALL, DOOR, WALL, FLOOR, WALL, FLOOR, WALL, FLOOR, WALL, FLOOR, WALL, FLOOR,
		FLOOR, FLOOR, FLOOR, BRICK, BRICK, BRICK, FLOOR, FLOOR, BRICK, BRICK, FLOOR, FLOOR, ENEMY3, FLOOR, FLOOR, BRICK, FLOOR, FLOOR, FLOOR,
	};
	level2 = {
		PLAYER, FLOOR, FLOOR, FLOOR, BRICK, BRICK, BRICK, BRICK, FLOOR, FLOOR, BRICK, BRICK, BRICK, BRICK, BRICK, FLOOR, FLOOR, BRICK, BRICK,
		FLOOR, WALL, FLOOR, WALL, BRICK, WALL, ENEMY2, WALL, FLOOR, WALL, BRICK, WALL, BRICK, WALL, FLOOR, WALL, FLOOR, WALL, ENEMY3,
		FLOOR, FLOOR, BRICK, BRICK, FLOOR, FLOOR, FLOOR, BRICK, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, BRICK, FLOOR, FLOOR, FLOOR,
		BRICK, WALL, BRICK, WALL, FLOOR, WALL, BRICK, WALL, BRICK, WALL, FLOOR, WALL, BRICK, WALL, FLOOR, WALL, BRICK, WALL, FLOOR,
		BRICK, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, BRICK, BRICK, FLOOR, FLOOR, BRICK, DOOR, BRICK, FLOOR, FLOOR, BRICK, BRICK, FLOOR,
		FLOOR, WALL, FLOOR, WALL, BRICK, WALL, FLOOR, WALL, BRICK, WALL, FLOOR, WALL, BRICK, WALL, FLOOR, WALL, BRICK, WALL, FLOOR,
		FLOOR, FLOOR, BRICK, FLOOR, BRICK, FLOOR, FLOOR, FLOOR, BRICK, BRICK, FLOOR, FLOOR, FLOOR, BRICK, BRICK, FLOOR, FLOOR, BRICK, BRICK,
		BRICK, WALL, FLOOR, WALL, FLOOR, WALL, FLOOR, WALL, FLOOR, WALL, BRICK, WALL, FLOOR, WALL, FLOOR, WALL, FLOOR, WALL, BRICK,
		BRICK, BRICK, ENEMY1, FLOOR, FLOOR, BRICK, BRICK, ENEMY2, FLOOR, FLOOR, BRICK, BRICK, FLOOR, FLOOR, FLOOR, FLOOR, ENEMY4, FLOOR, BRICK
	};
	level3 = {
	BRICK, BRICK, BRICK, FLOOR, BRICK, FLOOR, FLOOR, ENEMY1, FLOOR, FLOOR, FLOOR, BRICK, FLOOR, FLOOR, BRICK, FLOOR, BRICK, FLOOR, FLOOR,
	BRICK, WALL, FLOOR, WALL, BRICK, WALL, FLOOR, WALL, BRICK, WALL, FLOOR, WALL, FLOOR, WALL, BRICK, WALL, FLOOR, WALL, FLOOR,
	FLOOR, FLOOR, FLOOR, FLOOR, BRICK, FLOOR, BRICK, FLOOR, BRICK, BRICK, FLOOR, FLOOR, FLOOR, FLOOR, BRICK, ENEMY3, FLOOR, FLOOR, FLOOR,
	FLOOR, WALL, FLOOR, WALL, BRICK, WALL, FLOOR, WALL, BRICK, WALL, FLOOR, WALL, BRICK, WALL, FLOOR, WALL, BRICK, WALL, FLOOR,
	ENEMY3, FLOOR, FLOOR, FLOOR, BRICK, FLOOR, FLOOR, FLOOR, PLAYER, BRICK, BRICK, FLOOR, FLOOR, FLOOR, ENEMY2, FLOOR, FLOOR, FLOOR, BRICK,
	FLOOR, WALL, BRICK, WALL, FLOOR, WALL, FLOOR, WALL, FLOOR, WALL, FLOOR, WALL, FLOOR, WALL, FLOOR, WALL, BRICK, WALL, FLOOR,
	FLOOR, BRICK, BRICK, FLOOR, BRICK, FLOOR, FLOOR, FLOOR, FLOOR, BRICK, FLOOR, FLOOR, FLOOR, BRICK, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR,
	BRICK, WALL, FLOOR, WALL, BRICK, WALL, BRICK, WALL, BRICK, WALL, BRICK, WALL, BRICK, WALL, FLOOR, WALL, FLOOR, WALL, BRICK,
	DOOR, BRICK, BRICK, FLOOR, FLOOR, BRICK, FLOOR, ENEMY4, FLOOR, FLOOR, FLOOR, BRICK, BRICK, FLOOR, BRICK, FLOOR, FLOOR, BRICK, BRICK,
	};
	level4 = {
	FLOOR, BRICK, BRICK, BRICK, FLOOR, FLOOR, BRICK, FLOOR, BRICK, FLOOR, FLOOR, BRICK, BRICK, BRICK, ENEMY5, FLOOR, FLOOR, FLOOR, FLOOR,
	FLOOR, WALL, BRICK, WALL, FLOOR, WALL, BRICK, WALL, BRICK, WALL, FLOOR, WALL, BRICK, WALL, FLOOR, WALL, FLOOR, WALL, BRICK,
	ENEMY2, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, BRICK, BRICK, BRICK, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, BRICK, BRICK, FLOOR, FLOOR,
	BRICK, WALL, BRICK, WALL, FLOOR, WALL, FLOOR, WALL, FLOOR, WALL, FLOOR, WALL, FLOOR, WALL, DOOR, WALL, FLOOR, WALL, BRICK,
	FLOOR, BRICK, BRICK, BRICK, FLOOR, FLOOR, FLOOR, PLAYER, FLOOR, FLOOR, FLOOR, BRICK, BRICK, BRICK, FLOOR, FLOOR, FLOOR, BRICK, FLOOR,
	BRICK, WALL, BRICK, WALL, FLOOR, WALL, FLOOR, WALL, FLOOR, WALL, FLOOR, WALL, BRICK, WALL, BRICK, WALL, FLOOR, WALL, FLOOR,
	FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, BRICK, BRICK, BRICK, FLOOR, FLOOR, FLOOR, FLOOR, ENEMY1, FLOOR, BRICK, FLOOR, FLOOR, FLOOR,
	ENEMY5, WALL, BRICK, WALL, FLOOR, WALL, BRICK, WALL, BRICK, WALL, FLOOR, WALL, BRICK, WALL, FLOOR, WALL, BRICK, WALL, FLOOR,
	FLOOR, BRICK, BRICK, BRICK, FLOOR, FLOOR, BRICK, FLOOR, BRICK, FLOOR, FLOOR, BRICK, BRICK, FLOOR, FLOOR, BRICK, FLOOR, FLOOR,
	};
	level5 = {
	BRICK, BRICK, BRICK, WALL, FLOOR, BRICK, BRICK, FLOOR, FLOOR, BRICK, BRICK, ENEMY5, FLOOR, WALL, DOOR, FLOOR, BRICK, FLOOR, FLOOR,
	BRICK, WALL, BRICK, WALL, FLOOR, WALL, FLOOR, WALL, ENEMY2, WALL, FLOOR, WALL, FLOOR, WALL, BRICK, WALL, BRICK, WALL, FLOOR,
	BRICK, BRICK, FLOOR, FLOOR, BRICK, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, BRICK, FLOOR, FLOOR, BRICK, BRICK, FLOOR, FLOOR, BRICK,
	FLOOR, WALL, FLOOR, WALL, FLOOR, WALL, FLOOR, WALL, WALL, WALL, FLOOR, WALL, FLOOR, WALL, BRICK, WALL, WALL, WALL, WALL,
	ENEMY1, BRICK, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, BRICK, BRICK, WALL, FLOOR, FLOOR, FLOOR, FLOOR, BRICK, BRICK, FLOOR, FLOOR, FLOOR,
	FLOOR, WALL, FLOOR, WALL, FLOOR, WALL, FLOOR, WALL, BRICK, WALL, FLOOR, WALL, FLOOR, WALL, WALL, WALL, WALL, FLOOR, FLOOR,
	FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, BRICK, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, ENEMY5, BRICK, BRICK, BRICK, FLOOR, FLOOR, FLOOR, BRICK,
	WALL, WALL, ENEMY6, WALL, FLOOR, WALL, BRICK, WALL, FLOOR, WALL, FLOOR, WALL, BRICK, WALL, FLOOR, WALL, FLOOR, WALL, BRICK,
	BRICK, ENEMY4, FLOOR, FLOOR, FLOOR, BRICK, BRICK, FLOOR, PLAYER, FLOOR, FLOOR, BRICK, BRICK, FLOOR, BRICK, FLOOR, ENEMY6, FLOOR, BRICK,
	};
	level6 = {
	PLAYER, FLOOR, BRICK, FLOOR, FLOOR, BRICK, BRICK, FLOOR, FLOOR, ENEMY4, FLOOR, BRICK, DOOR, FLOOR, FLOOR, BRICK, FLOOR, FLOOR, FLOOR,
	FLOOR, WALL, FLOOR, WALL, FLOOR, WALL, BRICK, WALL, FLOOR, WALL, FLOOR, WALL, BRICK, WALL, BRICK, WALL, FLOOR, WALL, FLOOR,
	BRICK, BRICK, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, BRICK, BRICK, FLOOR, FLOOR, BRICK, BRICK, FLOOR, BRICK, BRICK, FLOOR,
	FLOOR, WALL, FLOOR, WALL, FLOOR, WALL, FLOOR, WALL, FLOOR, WALL, FLOOR, WALL, ENEMY5, WALL, BRICK, WALL, FLOOR, BRICK, BRICK,
	ENEMY5, FLOOR, BRICK, FLOOR, FLOOR, BRICK, FLOOR, FLOOR, FLOOR, BRICK, FLOOR, FLOOR, FLOOR, BRICK, FLOOR, FLOOR, FLOOR, ENEMY1, BRICK,
	FLOOR, WALL, BRICK, WALL, FLOOR, WALL, BRICK, WALL, FLOOR, WALL, BRICK, WALL, BRICK, WALL, BRICK, WALL, BRICK, WALL, FLOOR,
	BRICK, BRICK, FLOOR, BRICK, ENEMY2, FLOOR, BRICK, FLOOR, BRICK, BRICK, FLOOR, BRICK, BRICK, FLOOR, BRICK, FLOOR, FLOOR, BRICK, FLOOR,
	BRICK, WALL, FLOOR, WALL, FLOOR, WALL, FLOOR, WALL, BRICK, WALL, FLOOR, WALL, FLOOR, WALL, FLOOR, WALL, BRICK, WALL, FLOOR,
	ENEMY6, FLOOR, FLOOR, BRICK, BRICK, BRICK, FLOOR, BRICK, BRICK, BRICK, FLOOR, FLOOR, ENEMY5, FLOOR, FLOOR, BRICK, BRICK, FLOOR, FLOOR,
	};
	level7 = {
	FLOOR, FLOOR, FLOOR, BRICK, FLOOR, WALL, FLOOR, FLOOR, FLOOR, FLOOR, ENEMY2, BRICK, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, BRICK,
	FLOOR, WALL, FLOOR, WALL, FLOOR, WALL, FLOOR, WALL, FLOOR, WALL, FLOOR, WALL, FLOOR, WALL, ENEMY6, WALL, FLOOR, WALL, BRICK,
	FLOOR, WALL, FLOOR, BRICK, FLOOR, WALL, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, BRICK, FLOOR, WALL, FLOOR, WALL, BRICK, FLOOR, FLOOR,
	BRICK, WALL, FLOOR, WALL, FLOOR, WALL, FLOOR, WALL, FLOOR, WALL, WALL, WALL, FLOOR, WALL, BRICK, WALL, FLOOR, WALL, FLOOR,
	DOOR, WALL, ENEMY5, BRICK, FLOOR, FLOOR, FLOOR, PLAYER, FLOOR, FLOOR, FLOOR, BRICK, ENEMY2, WALL, BRICK, FLOOR, BRICK, FLOOR, BRICK,
	BRICK, WALL, FLOOR, WALL, WALL, WALL, FLOOR, WALL, FLOOR, WALL, FLOOR, WALL, FLOOR, WALL, BRICK, WALL, WALL, WALL, FLOOR,
	FLOOR, WALL, FLOOR, BRICK, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, WALL, FLOOR, BRICK, FLOOR, WALL, FLOOR, BRICK, FLOOR, FLOOR, FLOOR,
	ENEMY6, WALL, FLOOR, WALL, FLOOR, WALL, FLOOR, WALL, FLOOR, WALL, FLOOR, WALL, FLOOR, WALL, FLOOR, WALL, FLOOR, WALL, FLOOR,
	FLOOR, FLOOR, FLOOR, BRICK, ENEMY1, FLOOR, FLOOR, FLOOR, FLOOR, WALL, FLOOR, BRICK, FLOOR, FLOOR, FLOOR, BRICK, FLOOR, FLOOR, BRICK
	};
	level8 = {
	PLAYER, FLOOR, FLOOR, WALL, FLOOR, BRICK, BRICK, FLOOR, FLOOR, FLOOR, FLOOR, WALL, BRICK, BRICK, BRICK, FLOOR, FLOOR, BRICK, FLOOR,
	FLOOR, WALL, BRICK, WALL, FLOOR, WALL, BRICK, WALL, FLOOR, WALL, FLOOR, WALL, FLOOR, WALL, BRICK, WALL, BRICK, WALL, FLOOR,
	BRICK, BRICK, BRICK, WALL, FLOOR, FLOOR, BRICK, WALL, ENEMY5, FLOOR, FLOOR, WALL, FLOOR, ENEMY7, FLOOR, FLOOR, FLOOR, FLOOR, BRICK,
	BRICK, WALL, FLOOR, WALL, FLOOR, WALL, FLOOR, WALL, BRICK, WALL, FLOOR, WALL, BRICK, WALL, FLOOR, WALL, FLOOR, WALL, BRICK,
	BRICK, BRICK, ENEMY5, WALL, FLOOR, FLOOR, FLOOR, WALL, BRICK, BRICK, BRICK, WALL, BRICK, BRICK, BRICK, WALL, BRICK, FLOOR, FLOOR,
	FLOOR, WALL, FLOOR, WALL, WALL, WALL, FLOOR, WALL, FLOOR, WALL, WALL, WALL, FLOOR, WALL, FLOOR, WALL, FLOOR, WALL, FLOOR,
	FLOOR, FLOOR, BRICK, BRICK, BRICK, FLOOR, FLOOR, WALL, FLOOR, FLOOR, FLOOR, BRICK, FLOOR, FLOOR, FLOOR, WALL, BRICK, BRICK, ENEMY5,
	FLOOR, WALL, BRICK, WALL, BRICK, WALL, FLOOR, WALL, FLOOR, WALL, FLOOR, WALL, BRICK, WALL, FLOOR, WALL, FLOOR, FLOOR, BRICK,
	FLOOR, BRICK, FLOOR, FLOOR, FLOOR, FLOOR, ENEMY5, WALL, FLOOR, FLOOR, BRICK, BRICK, BRICK, FLOOR, ENEMY2, WALL, FLOOR, BRICK, DOOR
	};
	level9 = {
	PLAYER, FLOOR, FLOOR, BRICK, FLOOR, ENEMY2, FLOOR, WALL, FLOOR, BRICK, FLOOR, FLOOR, FLOOR, ENEMY7, FLOOR, FLOOR, BRICK, FLOOR, FLOOR,
	FLOOR, WALL, BRICK, WALL, BRICK, WALL, BRICK, WALL, FLOOR, WALL, FLOOR, WALL, FLOOR, WALL, FLOOR, WALL, FLOOR, WALL, BRICK,
	FLOOR, WALL, BRICK, WALL, FLOOR, BRICK, FLOOR, WALL, FLOOR, WALL, FLOOR, WALL, FLOOR, BRICK, FLOOR, FLOOR, FLOOR, ENEMY1, FLOOR,
	FLOOR, WALL, ENEMY6, WALL, FLOOR, WALL, FLOOR, WALL, FLOOR, WALL, FLOOR, WALL, WALL, WALL, WALL, WALL, FLOOR, WALL, FLOOR,
	FLOOR, WALL, FLOOR, WALL, ENEMY1, FLOOR, FLOOR, FLOOR, FLOOR, WALL, ENEMY5, BRICK, FLOOR, FLOOR, FLOOR, FLOOR, BRICK, FLOOR, FLOOR,
	FLOOR, WALL, WALL, WALL, BRICK, WALL, FLOOR, WALL, WALL, WALL, FLOOR, WALL, FLOOR, WALL, FLOOR, WALL, BRICK, WALL, FLOOR,
	BRICK, WALL, FLOOR, FLOOR, FLOOR, WALL, FLOOR, BRICK, ENEMY6, WALL, FLOOR, BRICK, FLOOR, ENEMY2, FLOOR, WALL, FLOOR, BRICK, DOOR,
	BRICK, WALL, FLOOR, WALL, FLOOR, WALL, FLOOR, WALL, FLOOR, WALL, FLOOR, WALL, FLOOR, WALL, FLOOR, WALL, FLOOR, WALL, BRICK,
	FLOOR, FLOOR, ENEMY5, FLOOR, FLOOR, WALL, FLOOR, FLOOR, ENEMY5, WALL, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, WALL, FLOOR, BRICK, BRICK
	};

	std::ifstream read("../Data/unlockedLevels.dat");
	read >> unlockedLevelNumber;
	currentLevel = 1;
}

LevelManager::~LevelManager() {
}

int LevelManager::getCurrentLevel() {
	return currentLevel;
}

void LevelManager::setCurrentLevel(int x) {
	currentLevel = x;
}

int LevelManager::getUnlockedLevelNumber() {
	return unlockedLevelNumber;
}

void LevelManager::increaseUnlockedLevelNumber() {
	if (currentLevel >= unlockedLevelNumber) {
		unlockedLevelNumber++;
		std::ofstream write("../Data/unlockedLevels.dat");
		write << unlockedLevelNumber;
	}
}

std::vector<int> LevelManager::getLevelTiles() {
	switch (currentLevel) {
	case 0:
		return multiplayerLevel;
	case 1:
		return level1;
	case 2:
		return level2;
	case 3:
		return level3;
	case 4:
		return level4;
	case 5:
		return level5;
	case 6:
		return level6;
	case 7:
		return level7;
	case 8:
		return level8;
	case 9:
		return level9;
	default:
		return level1;
	}
}
